import { Router } from 'express';
import healthRoutes from './health.js';
import clientRoutes from './clients.js';
import metaRoutes from './meta.js';
import aiRoutes from './ai.js';
import reportRoutes from './reports.js';
import commentRoutes from './comments.js';
import profileRoutes from './profiles.js';
import copyRoutes from './copy.js';
import taskRoutes from './tasks.js';
import calendarRoutes from './calendar.js';
import approvalRoutes from './approvals.js';
import leadsRoutes from './leads.js';
import interactionsRoutes from './interactions.js';
import proposalsRoutes from './proposals.js';
import outboundRoutes from './outbound.js';
import onboardingRoutes from './onboarding.js';
import dashboardRoutes from './dashboard.js';
import moodboardRoutes from './moodboards.js';
import organizationRoutes from './organizations.js';
import invitationRoutes from './invitations.js';
import teamRoutes from './teams.js';
import chatRoutes from './chat.js';

const router = Router();

router.use('/health', healthRoutes);
router.use('/clients', clientRoutes);
router.use('/meta', metaRoutes);
router.use('/ai', aiRoutes);
router.use('/reports', reportRoutes);
router.use('/reports', commentRoutes);
router.use('/profiles', profileRoutes);
router.use('/copy', copyRoutes);
router.use('/tasks', taskRoutes);
router.use('/calendar', calendarRoutes);
router.use('/approvals', approvalRoutes);
router.use('/leads', leadsRoutes);
router.use('/interactions', interactionsRoutes);
router.use('/proposals', proposalsRoutes);
router.use('/outbound', outboundRoutes);
router.use('/onboarding', onboardingRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/moodboards', moodboardRoutes);
router.use('/organizations', organizationRoutes);
router.use('/invitations', invitationRoutes);
router.use('/teams', teamRoutes);
router.use('/chat', chatRoutes);

export default router;
